on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_job:
    runs-on: ubuntu-latest
    env:
      TEST: ${{ secrets.TEST_SECRET }}        
    steps:
      - name: Test Job
        shell: bash
        run: |
          echo "hello world"
